name: Playwright Tests
on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ develop, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Smoke Tests
      run: npx playwright test --grep @Smoke
    - name: Upload Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 30
    - name: Upload Traces
      if: failure()
      uses: actions/upload-artifact@v4
      with:
       name: playwright-traces
       path: test-results/
